apiVersion: run.tanzu.vmware.com/v1alpha1      
kind: TanzuKubernetesCluster                   
metadata:
  name: testcluster                         
  namespace: nonprod-appteam1 
spec:
  distribution:
    fullVersion: v1.19.7+vmware.1-tkg.1.fc82c41
  topology:
    controlPlane:
      count: 1                                 
      class: best-effort-small                 
      storageClass: tanzu
    workers:
      count: 1                                
      class: best-effort-small                 
      storageClass: tanzu        
      volumes:
        - name: containerd
          mountPath: /var/lib
          capacity:
            storage: 50Gi 
